using System.Collections.Generic;
using System.Linq;

namespace ProjectON
{
    internal enum ProjectONLanguage
    {
        English,
        Korean
    }

    internal static class ProjectONStringTable
    {
        private static readonly Dictionary<string, string> Korean = new Dictionary<string, string>
        {
            { "Language\nKorean", "언어\n한국어" },
            { "Language\nEnglish", "언어\nEnglish" },
            { "Language changed to Korean.", "언어가 한국어로 변경되었습니다." },
            { "Language changed to English.", "Language changed to English." },

            { "Save\nF5", "저장\nF5" },
            { "Load\nF9", "불러오기\nF9" },
            { "Pause\nSpace", "일시정지\nSpace" },
            { "Speed\n-/+", "속도\n-/+" },
            { "Start-\nF6", "취침-\nF6" },
            { "Start+\nF7", "취침+\nF7" },
            { "Wake-\nF8", "기상-\nF8" },
            { "Wake+\nF10", "기상+\nF10" },
            { "Pri -\n[", "우선-\n[" },
            { "Pri +\n]", "우선+\n]" },
            { "Cancel\nDel", "취소\nDel" },
            { "Switch\nON", "스위치\n켜짐" },
            { "Switch\nOFF", "스위치\n꺼짐" },
            { "Door\nOPEN", "문\n열림" },
            { "Door\nCLOSED", "문\n닫힘" },
            { "Load Save", "저장 불러오기" },
            { "New Run", "새 런" },
            { "Continue", "계속" },

            { "Colony charter complete. Expand into the asteroid and keep the colony alive.", "콜로니 헌장이 완료되었습니다. 소행성으로 확장하며 생존을 유지하세요." },
            { "Build a safe barracks: 12 floor tiles and one bed per duplicant.", "안전한 막사를 만드세요: 바닥 12칸과 복제체마다 침대 1개가 필요합니다." },
            { "Build an Outhouse so duplicants can relieve bladder pressure safely.", "복제체가 안전하게 볼일을 볼 수 있도록 재래식 화장실을 지으세요." },
            { "Build a Wash Basin near the outhouse so duplicants clean germs before getting sick.", "병에 걸리기 전에 손을 씻도록 화장실 근처에 세면대를 지으세요." },
            { "Store clean water so the Wash Basin can remove germs from duplicants.", "세면대가 병균을 제거할 수 있도록 깨끗한 물을 확보하세요." },
            { "Let a germy duplicant wash hands at the Wash Basin to prove hygiene control.", "병균에 노출된 복제체가 세면대에서 손을 씻게 하세요." },
            { "Build a Compost and process polluted dirt from outhouses or spoiled food.", "퇴비장을 지어 화장실이나 상한 음식에서 나온 오염된 흙을 처리하세요." },
            { "Build a Storage Bin so mined dirt, metal, algae, and coal have room to accumulate.", "채굴한 흙, 금속, 조류, 석탄을 보관할 저장고를 지으세요." },
            { "Use Sweep on mined debris so duplicants move resources into storage.", "채굴 잔해에 Sweep을 지정해 복제체가 자원을 저장소로 옮기게 하세요." },
            { "Dig natural tiles to create debris, then Sweep it into storage.", "자연 타일을 파서 잔해를 만들고 저장소로 Sweep하세요." },
            { "Secure water: build a water pump beside a blue water pocket.", "물을 확보하세요: 파란 물웅덩이 옆에 물 펌프를 지으세요." },
            { "Build Liquid Pipes and a Liquid Vent to move water through plumbing.", "액체 배관과 액체 배출구를 지어 물을 이동시키세요." },
            { "Start research: build a research station and complete Air Systems.", "연구를 시작하세요: 연구소를 짓고 공기 시스템을 완료하세요." },
            { "Stabilize oxygen: build and fuel an oxygen diffuser.", "산소를 안정화하세요: 산소 발생기를 짓고 조류를 공급하세요." },
            { "Control pressure: build a Manual Airlock to slow gas and heat exchange between rooms.", "압력을 제어하세요: 수동 에어록으로 방 사이의 기체와 열 교환을 늦추세요." },
            { "Inspect a Manual Airlock and close it to seal pathing, gas, and heat.", "수동 에어록을 Inspect한 뒤 닫아서 이동, 기체, 열을 차단하세요." },
            { "Build Gas Pump, Gas Pipe, and Gas Vent to route breathable air.", "가스 펌프, 가스 배관, 가스 배출구를 지어 숨쉴 공기를 라우팅하세요." },
            { "Build a Liquid Reservoir or Gas Reservoir on a pipe network to buffer flow.", "배관망에 액체 저장소나 가스 저장소를 지어 흐름을 완충하세요." },
            { "Build an Electrolyzer and Carbon Skimmer to process water into oxygen and scrub CO2.", "전해조와 탄소 스키머를 지어 물을 산소로 바꾸고 CO2를 제거하세요." },
            { "Build a Water Sieve to recycle polluted water back into clean water.", "정수기를 지어 오염된 물을 깨끗한 물로 재활용하세요." },
            { "Build a Medical Cot to treat sick or injured duplicants.", "아프거나 다친 복제체를 치료할 의료 침대를 지으세요." },
            { "Research Food Preparation, then build a Microbe Musher.", "음식 준비를 연구한 뒤 미생물 분쇄기를 지으세요." },
            { "Preserve food: build and power a Refrigerator before stored meals spoil.", "음식을 보존하세요: 식사가 상하기 전에 냉장고를 짓고 전력을 공급하세요." },
            { "Build one Mess Table per duplicant so meals improve morale.", "식사가 사기를 올리도록 복제체마다 식탁 1개를 지으세요." },
            { "Train a duplicant to Skill Lv 3 by completing skilled work.", "숙련 작업을 완료해 복제체 하나를 스킬 Lv 3까지 훈련하세요." },
            { "Decorate living areas with Decor Plants to raise morale and reduce stress.", "생활 구역을 장식 식물로 꾸며 사기를 올리고 스트레스를 줄이세요." },
            { "Create a power buffer: add battery capacity and store 75 power.", "전력 완충을 만드세요: 배터리 용량을 늘리고 전력 75를 저장하세요." },
            { "Wire the power grid: connect generators, batteries, and powered machines.", "전력망을 배선하세요: 발전기, 배터리, 전력 기계를 연결하세요." },
            { "Research Power Regulation so the grid can handle heavier machine loads.", "전력 제어를 연구해 전력망이 더 큰 기계 부하를 견디게 하세요." },
            { "Build a Coal Generator, mine coal, and let it produce backup power.", "석탄 발전기를 짓고 석탄을 채굴해 예비 전력을 생산하세요." },
            { "Build and power a Rock Crusher, then refine metal ore into Refined Metal.", "암석 분쇄기를 짓고 전력을 공급해 금속 원석을 제련 금속으로 바꾸세요." },
            { "Build four Insulated Tiles to separate living rooms from dangerous heat and gas.", "단열 타일 4개로 생활 공간을 위험한 열과 기체에서 분리하세요." },
            { "Create separate Barracks and Mess Hall rooms with airlocks or insulated walls.", "에어록이나 단열 벽으로 막사와 식당을 별도 방으로 만드세요." },
            { "Use Deconstruct on a building or conduit to recover materials and reconfigure the base.", "건물이나 도관에 Deconstruct를 사용해 재료를 회수하고 기지를 재구성하세요." },
            { "Keep a Printing Pod open until it prints a fourth duplicant.", "프린팅 포드를 열어 네 번째 복제체가 출력될 때까지 유지하세요." },
            { "Automate power: research Power Regulation, then link a Smart Battery to a generator with Automation Wire.", "전력을 자동화하세요: 전력 제어를 연구하고 스마트 배터리를 자동화 전선으로 발전기에 연결하세요." },
            { "Build Bunker Doors above exposed surface infrastructure before the next meteor shower.", "다음 운석우 전에 노출된 지상 설비 위에 벙커 문을 지으세요." },
            { "Survive until cycle 5 with at least one active duplicant.", "활동 가능한 복제체 1명 이상으로 5사이클까지 생존하세요." },
            { "Colony failed. Load a save or start a new run from the editor.", "콜로니가 실패했습니다. 저장 파일을 불러오거나 새 런을 시작하세요." },
            { "Colony failed. Load a save or start a new run.", "콜로니가 실패했습니다. 저장 파일을 불러오거나 새 런을 시작하세요." },

            { "Colony online.", "콜로니 온라인." },
            { "Stable.", "안정적." },
            { "Scenario: ", "시나리오: " },
            { "Colony failed", "콜로니 실패" },
            { "Colony Charter complete", "콜로니 헌장 완료" },
            { "Colony Charter", "콜로니 헌장" },
            { "Phase: ", "단계: " },
            { "Next: ", "다음: " },
            { "Critical: ", "위험: " },
            { "Charter milestone reward delivered: ", "헌장 목표 보상 지급: " },
            { "Freeplay", "자유 플레이" },
            { "Survival", "생존" },
            { "Base Systems", "기지 시스템" },
            { "Industry", "산업" },
            { "Automation", "자동화" },
            { "Surface & Space", "지표면과 우주" },
            { "Expand, optimize, and survive indefinitely.", "확장, 최적화, 장기 생존을 이어가세요." },
            { "Beds, toilets, oxygen, food, and water.", "침대, 화장실, 산소, 식량, 물을 확보하세요." },
            { "Research, rooms, morale, power, and storage.", "연구, 방, 사기, 전력, 저장을 갖추세요." },
            { "Pipes, vents, suits, refining, and backup power.", "배관, 환기, 대기복, 제련, 예비 전력을 구축하세요." },
            { "Sensors, sweepers, shipping, ranching, and vents.", "센서, 청소기, 물류, 목축, 자연 분출구를 자동화하세요." },
            { "Solar, steam, scanners, bunker doors, and final charter.", "태양광, 증기, 스캐너, 벙커 문으로 최종 헌장을 완료하세요." },
            { " more", "개 더" },
            { " food", " 식량" },
            { " water", " 물" },
            { " dirt", " 흙" },
            { " metal", " 금속" },
            { " algae", " 조류" },
            { " coal", " 석탄" },
            { " refined metal", " 제련 금속" },
            { " research", " 연구" },
            { " power capacity", " 전력 용량" },
            { "Simulation paused.", "시뮬레이션 일시정지." },
            { "Simulation resumed.", "시뮬레이션 재개." },
            { "Game saved.", "게임 저장됨." },
            { "Autosaved colony.", "콜로니 자동 저장됨." },
            { "Game loaded.", "게임 불러옴." },
            { "No save file found.", "저장 파일이 없습니다." },
            { "Save file is incompatible.", "저장 파일이 호환되지 않습니다." },
            { "World data restored.", "월드 데이터 복구됨." },
            { "New colony started.", "새 콜로니가 시작되었습니다." },
            { "Freeplay continues.", "자유 플레이를 계속합니다." },
            { "Colony charter complete. Freeplay continues.", "콜로니 헌장 완료. 자유 플레이가 계속됩니다." },
            { "All duplicants are incapacitated. Load a save or start a new run.", "모든 복제체가 행동 불능입니다. 저장 파일을 불러오거나 새 런을 시작하세요." },
            { "The colony charter is complete. Continue freeplay, load a save, or start a new run.", "콜로니 헌장이 완료되었습니다. 자유 플레이를 계속하거나 저장 파일을 불러오거나 새 런을 시작하세요." },
            { "Planter needs floor support.", "화분은 바닥 지지가 필요합니다." },
            { "Decor Plant needs floor support.", "장식 식물은 바닥 지지가 필요합니다." },

            { "Objective: ", "목표: " },
            { "Tech: ", "기술: " },
            { "Alerts: ", "경고: " },
            { "Overlay: Gas", "오버레이: 가스" },
            { "Overlay: Power", "오버레이: 전력" },
            { "Mode: ", "모드: " },
            { "Overlay: ", "오버레이: " },
            { "Rooms: ", "방: " },
            { "Workers: ", "복제체: " },
            { "Cycle ", "사이클 " },
            { "PAUSED", "일시정지" },
            { "Schedule ", "일정 " },
            { "Sleep ", "수면 " },
            { "Alert: ", "경고: " },
            { "Down ", "쓰러짐 " },
            { "Low morale ", "낮은 사기 " },
            { "Power Regulation", "전력 제어" },
            { "Air Systems", "공기 시스템" },
            { "Food Preparation", "음식 준비" },
            { "Air ", "공기 " },
            { "Food ", "식량 " },
            { " Power ", " 전력 " },
            { "Research ", "연구 " },
            { "Jobs ", "작업 " },
            { "Errands ", "심부름 " },
            { "Active ", "활동 " },
            { "Open ", "대기 " },
            { "Reachable ", "도달 가능 " },
            { "Assigned ", "배정 " },
            { "Invalid ", "무효 " },
            { "Focus: ", "중점: " },
            { "Categories (open/assigned/blocked): ", "분류(대기/배정/막힘): " },
            { "Oldest: ", "최장 대기: " },
            { "No active duplicants.", "활동 가능한 복제체가 없습니다." },
            { "Invalid jobs need cancellation.", "무효 작업을 취소해야 합니다." },
            { "Build access to blocked work cells.", "막힌 작업 칸까지 접근로를 지으세요." },
            { "No queued errands.", "대기 중인 심부름이 없습니다." },
            { "Duplicants are working.", "복제체가 작업 중입니다." },
            { "Reduce backlog with priorities.", "우선순위로 밀린 작업을 줄이세요." },
            { "No queued errands. Use Dig/Build/Operate commands to create work.", "대기 중인 심부름이 없습니다. Dig/Build/Operate 명령으로 작업을 만드세요." },
            { "Construction", "건설" },
            { "Life Support", "생명 유지" },
            { "Food Ops", "식량 작업" },
            { "Power Ops", "전력 작업" },
            { "Research Ops", "연구 작업" },
            { "Maintenance", "정비" },
            { "Ranching", "목축" },
            { "Morale Care", "사기 관리" },
            { " priority ", " 우선순위 " },
            { "none", "없음" },
            { "  Steam ", "  증기 " },
            { "  Cl ", "  염소 " },
            { "  NG ", "  천연가스 " },
            { "  Metal ", "  금속 " },
            { "  Ref ", "  제련 " },
            { "  SuitO2 ", "  복산소 " },
            { "  SuitX ", "  복통과 " },
            { "  SuitBlk ", "  복차단 " },
            { "  LFlow ", "  액흐름 " },
            { "  Phase ", "  상변화 " },
            { " Vapor ", " 증발 " },
            { "  Chlor ", "  염소 " },
            { "  Flood ", "  침수 " },
            { "  OHeat ", "  과열 " },
            { "  Press ", "  압력 " },
            { "  Therm ", "  온도노출 " },
            { " Inj ", " 부상 " },
            { "  Store ", "  저장 " },
            { "  Loose ", "  잔해 " },
            { "  PW ", "  오염수 " },
            { " PWGas ", " 오염수증기 " },
            { "  PD ", "  오염흙 " },
            { "  Wash ", "  손씻기 " },
            { "  Pipe ", "  배관 " },
            { " Burst ", " 파열 " },
            { " F/B ", " 동결/비등 " },
            { "  LRes ", "  액저장 " },
            { " RBrst ", " 저장파열 " },
            { "  Vent ", "  배출 " },
            { "  GRes ", "  가스저장 " },
            { " Fresh ", " 신선도 " },
            { " BadMeal ", " 상한식사 " },
            { "  Morale ", "  사기 " },
            { " Def ", " 부족 " },
            { " Stress ", " 스트레스 " },
            { "  Print ", "  출력 " },
            { "  Grid ", "  전력망 " },
            { " Load ", " 부하 " },
            { " Over ", " 과부하 " },
            { "  Auto ", "  자동화 " },
            { " Sw ", " 스위치 " },
            { "  Door ", "  문 " },
            { "  Valve ", "  밸브 " },
            { " Flow ", " 흐름 " },
            { "  VentW ", "  분출수 " },
            { " VentH2 ", " 분출H2 " },
            { " VentNG ", " 분출천연가스 " },
            { "  Rescue ", "  구조 " },
            { " AutoSwp ", " 자동청소 " },
            { " Ship ", " 물류 " },
            { "  H2Gen ", "  수소발전 " },
            { " NGGen ", " 가스발전 " },
            { " SteamTur ", " 증기터빈 " },
            { " Meteor ACTIVE", " 운석우 진행 " },
            { " Meteor in", " 운석까지 " },
            { " Scan ", " 스캔 " },
            { "  H2Filt ", "  수소필터 " },
            { "  Hatch ", "  해치 " },
            { " open)", " 대기)" },
            { "RP", "점" },
            { "Open", "열림" },
            { "closed", "닫힘" },

            { "Select a tile.", "타일을 선택하세요." },
            { "Tile ", "타일 " },
            { "Temp ", "온도 " },
            { "Pressure ", "압력 " },
            { "DANGEROUS", "위험" },
            { "HIGH", "높음" },
            { "Power Wire: connected", "전력 전선: 연결됨" },
            { "Power Wire: unpowered", "전력 전선: 전력 없음" },
            { "Machine power: wired", "기계 전력: 연결됨" },
            { "Machine power: no wire connection", "기계 전력: 전선 연결 없음" },
            { "Automation Wire: green signal", "자동화 전선: 녹색 신호" },
            { "Automation Wire: red signal", "자동화 전선: 적색 신호" },
            { "Automation Wire: no signal source", "자동화 전선: 신호원 없음" },
            { "Signal green", "신호 녹색" },
            { "Signal red", "신호 적색" },
            { "Liquid Pipe: ", "액체 배관: " },
            { "Gas Pipe: ", "가스 배관: " },
            { "Condition ", "상태 " },
            { "Equipment in good condition.", "장비 상태 양호." },
            { "Broken: disabled until repaired", "고장: 수리 전까지 비활성" },
            { "Damaged: Repair restores operation reliability.", "손상됨: 수리하면 작동 안정성이 회복됩니다." },
            { "Submerged: disabled and taking water damage.", "침수됨: 비활성화되고 물 피해를 받습니다." },
            { "Germs ", "병균 " },
            { "Decor ", "장식 " },
            { "Room ", "방 " },
            { "Size ", "크기 " },
            { "Room boundary sealed.", "방 경계가 밀폐됨." },
            { "Room open to asteroid.", "방이 소행성에 열려 있음." },
            { "Job: ", "작업: " },
            { "Target ", "대상 " },
            { "Priority ", "우선순위 " },
            { "Waiting ", "대기 " },
            { "Effective priority ", "적용 우선순위 " },
            { "Progress ", "진행률 " },
            { "Health ", "체력 " },
            { "Calories ", "칼로리 " },
            { "Stress ", "스트레스 " },
            { "Fatigue ", "피로 " },
            { "Bladder ", "방광 " },
            { "Exposure ", "노출 " },
            { "Sickness ", "질병 " },
            { "Local decor ", "지역 장식 " },
            { "Incapacitated", "무력화" },
            { "Needs rescue to a Medical Cot.", "의료 침대로 구조해야 합니다." },

            { "Basic Room", "기본 방" },
            { "Open Area", "개방 구역" },
            { "Barracks", "막사" },
            { "Mess Hall", "식당" },
            { "Washroom", "화장실" },
            { "Clinic", "진료실" },
            { "Recreation Room", "휴게실" },
            { "Machine Room", "기계실" },
            { "Storage Room", "창고" },
            { "Mixed Room", "혼합 방" },

            { "Manual Generator", "수동 발전기" },
            { "Oxygen Diffuser", "산소 발생기" },
            { "Smart Battery", "스마트 배터리" },
            { "Power Transformer", "전력 변압기" },
            { "Coal Generator", "석탄 발전기" },
            { "Hydrogen Generator", "수소 발전기" },
            { "Natural Gas Generator", "천연가스 발전기" },
            { "Steam Turbine", "증기 터빈" },
            { "Solar Panel", "태양광 패널" },
            { "Bunker Door", "벙커 문" },
            { "Space Scanner", "우주 스캐너" },
            { "Hydrogen Filter", "수소 필터" },
            { "Rock Crusher", "암석 분쇄기" },
            { "Atmo Suit Dock", "대기복 도크" },
            { "Atmo Suit Checkpoint", "대기복 체크포인트" },
            { "Insulated Tile", "단열 타일" },
            { "Printing Pod", "프린팅 포드" },
            { "Water Pump", "물 펌프" },
            { "Bottle Emptier", "병 비우개" },
            { "Research Station", "연구소" },
            { "Microbe Musher", "미생물 분쇄기" },
            { "Air Deodorizer", "공기 탈취기" },
            { "Medical Cot", "의료 침대" },
            { "Space Heater", "공간 히터" },
            { "Thermo Regulator", "열 조절기" },
            { "Wash Basin", "세면대" },
            { "Massage Table", "마사지 침대" },
            { "Manual Airlock", "수동 에어록" },
            { "Storage Bin", "저장고" },
            { "Auto-Sweeper", "자동 청소기" },
            { "Shipping Rail", "운송 레일" },
            { "Conveyor Loader", "컨베이어 적재기" },
            { "Conveyor Chute", "컨베이어 배출구" },
            { "Signal Switch", "신호 스위치" },
            { "Liquid Pipe Sensor", "액체 배관 센서" },
            { "Liquid Shutoff", "액체 차단기" },
            { "Liquid Reservoir", "액체 저장소" },
            { "Liquid Vent", "액체 배출구" },
            { "Gas Pipe Sensor", "가스 배관 센서" },
            { "Gas Shutoff", "가스 차단기" },
            { "Gas Reservoir", "가스 저장소" },
            { "Gas Pump", "가스 펌프" },
            { "Gas Pipe", "가스 배관" },
            { "Gas Vent", "가스 배출구" },
            { "Steam Vent", "증기 분출구" },
            { "Hydrogen Vent", "수소 분출구" },
            { "Natural Gas Vent", "천연가스 분출구" },
            { "Ranching Station", "목축 스테이션" },
            { "Electrolyzer", "전해조" },
            { "Carbon Skimmer", "탄소 스키머" },
            { "Water Sieve", "정수기" },
            { "Mess Table", "식탁" },
            { "Decor Plant", "장식 식물" },

            { "Inspect", "조사" },
            { "Dig", "채굴" },
            { "Ladder", "사다리" },
            { "Floor", "바닥" },
            { "Battery", "배터리" },
            { "Deconstruct", "철거" },
            { "Mop", "닦기" },
            { "Repair", "수리" },
            { "Sweep", "청소" },
            { "Bed", "침대" },
            { "Planter", "화분" },
            { "Outhouse", "재래식 화장실" },
            { "Compost", "퇴비장" },
            { "Refrigerator", "냉장고" },
            { "Dirt", "흙" },
            { "Rock", "암석" },
            { "Sand", "모래" },
            { "Metal Ore", "금속 원석" },
            { "Algae", "조류" },
            { "Coal", "석탄" },
            { "Ice", "얼음" },
            { "Slime", "슬라임" },
            { "Regolith", "표토" },
            { "Water", "물" },
            { "Empty", "빈 공간" },

            { "Gas\nF1", "가스\nF1" },
            { "Temp\nF2", "온도\nF2" },
            { "Power\nF3", "전력\nF3" },
            { "Germs\nF4", "병균\nF4" },
            { "Decor\nView", "장식\n보기" },
            { "Rooms\nView", "방\n보기" },
            { "Pipe\nF11", "배관\nF11" },
            { "Vent\nF12", "환기\nF12" },
            { "Ship\nView", "물류\n보기" },
            { "Diffuser", "산소기" },
            { "Generator", "발전기" },
            { "Smart", "스마트" },
            { "Trans", "변압기" },
            { "CoalGen", "석탄발전" },
            { "H2 Gen", "수소발전" },
            { "NG Gen", "가스발전" },
            { "Turbine", "터빈" },
            { "Solar", "태양광" },
            { "Bunker", "벙커" },
            { "Scanner", "스캐너" },
            { "H2 Filt", "수소필터" },
            { "Crusher", "분쇄기" },
            { "SuitDock", "복도크" },
            { "SuitChk", "복검문" },
            { "InsTile", "단열" },
            { "Decon", "철거" },
            { "Pod", "포드" },
            { "Farm", "농장" },
            { "Pump", "펌프" },
            { "Bottle", "병비움" },
            { "Musher", "분쇄기" },
            { "Deodor", "탈취기" },
            { "Med Cot", "의료침대" },
            { "Heater", "히터" },
            { "Cooler", "냉각기" },
            { "Wire", "전선" },
            { "Auto\nM1", "자동화\nM1" },
            { "Auto\nLOCK", "자동화\n잠김" },
            { "Toilet", "화장실" },
            { "Basin", "세면대" },
            { "Massage", "마사지" },
            { "Airlock", "에어록" },
            { "Fridge", "냉장고" },
            { "Bin", "저장고" },
            { "SweepR", "청소기" },
            { "Rail", "레일" },
            { "Loader", "적재기" },
            { "Chute", "배출구" },
            { "Signal", "신호" },
            { "L Sens", "액센서" },
            { "L Shut", "액차단" },
            { "L Res", "액저장" },
            { "Vent", "배출" },
            { "GasP", "가스펌프" },
            { "GasLn", "가스관" },
            { "G Sens", "가스센서" },
            { "G Shut", "가스차단" },
            { "G Res", "가스저장" },
            { "GasV", "가스배출" },
            { "Ranch", "목축" },
            { "Elect", "전해조" },
            { "Skim", "스키머" },
            { "Sieve", "정수기" },
            { "Mess", "식탁" },
            { "LOCK", "잠김" },
            { "Temperature", "온도" },
            { "Gas", "가스" },
            { "Power", "전력" },
            { "Germs", "병균" },
            { "Decor", "장식" },
            { "Plumbing", "배관" },
            { "Ventilation", "환기" },
            { "Logistics", "물류" },
            { "Rooms", "방" },
            { "Legend: ", "범례: " },
            { "Cold", "차가움" },
            { "Comfort", "쾌적" },
            { "Hot", "뜨거움" },
            { "Steam risk", "증기 위험" },
            { "Powered wire", "전력 공급 전선" },
            { "Unpowered wire", "전력 없음 전선" },
            { "Overload", "과부하" },
            { "Machine running", "기계 작동" },
            { "Low germs", "낮은 병균" },
            { "High germs", "높은 병균" },
            { "Polluted oxygen", "오염된 산소" },
            { "Clean tile", "깨끗한 칸" },
            { "Liquid pipe", "액체 배관" },
            { "Reservoir fill", "저장소 채움" },
            { "Green sensor", "초록 신호" },
            { "Closed or blocked", "닫힘 또는 막힘" },
            { "Oxygen pipe", "산소 배관" },
            { "Hydrogen pipe", "수소 배관" },
            { "Natural gas pipe", "천연가스 배관" },
            { "Shipping rail", "운송 레일" },
            { "Loader powered", "적재기 전력 공급" },
            { "Loader blocked", "적재기 막힘" },
            { "Auto-sweeper", "자동 청소기" },
            { "Decor source", "장식 원천" },
            { "Decor aura", "장식 범위" },
            { "No decor", "장식 없음" },
            { "Morale help", "사기 보조" },
            { "Oxygen", "산소" },
            { "Carbon dioxide", "이산화탄소" },
            { "Hydrogen", "수소" },

            { "Idle", "대기" },
            { "Moving", "이동 중" },
            { "Sleeping", "수면 중" },
            { "Eating", "식사 중" },
            { "Relaxing", "휴식 중" },
            { "Using Outhouse", "화장실 사용 중" },
            { "Washing Hands", "손 씻는 중" },
            { "Receiving Treatment", "치료 받는 중" },
            { "Stress Break", "스트레스 폭발" },
            { "Recovering", "회복 중" },
            { "Avoiding Water", "물 회피 중" },
            { "Trapped in Water", "물에 갇힘" },
            { "Waiting for Atmo Suit", "대기복 대기 중" },
            { "Dodging Falling Sand", "낙하 모래 회피 중" },
            { "Dodging Meteor Debris", "운석 파편 회피 중" },
            { "Going to ", "이동: " },
            { "Build ", "건설 " },
            { "Harvest", "수확" },
            { "Cook", "요리" },
            { "Sleep", "수면" },
            { "Treatment", "치료" },
            { "Use Outhouse", "화장실 사용" },
            { "Wash Hands", "손 씻기" },
            { "Tend Crop", "작물 돌보기" },
            { "Empty Bottle", "병 비우기" },
            { "Operate Generator", "발전기 운전" },
            { "Refine Metal", "금속 제련" },
            { "Groom Hatch", "해치 돌보기" },
            { "low oxygen", "산소 부족" },
            { "unreachable jobs", "도달 불가 작업" },
            { "duplicant down", "복제체 쓰러짐" },
            { "no rescue cot", "구조용 침대 없음" },
            { "polluted oxygen", "오염된 산소" },
            { "germy duplicants", "병균 노출 복제체" },
            { "no wash basin", "세면대 없음" },
            { "low morale", "낮은 사기" },
            { "hydrogen buildup", "수소 축적" },
            { "natural gas buildup", "천연가스 축적" },
            { "mixed H2 pipe", "혼합 수소 배관" },
            { "high CO2", "CO2 높음" },
            { "no airlocks", "에어록 없음" },
            { "airlocks open", "에어록 열림" },
            { "unstable sand", "불안정한 모래" },
            { "moving liquid", "이동 중인 액체" },
            { "melting ice", "녹는 얼음" },
            { "freezing water", "어는 물" },
            { "steam cloud", "증기 구름" },
            { "untapped steam power", "미활용 증기 전력" },
            { "chlorine pocket", "염소 포켓" },
            { "submerged equipment", "침수 장비" },
            { "flooded power wire", "침수 전력 전선" },
            { "equipment overheating", "장비 과열" },
            { "base too hot", "기지가 너무 뜨거움" },
            { "base too cold", "기지가 너무 추움" },
            { "dangerous temperatures", "위험 온도" },
            { "thermal injury", "열/냉기 부상" },
            { "temperature exposure", "온도 노출" },
            { "dangerous pressure", "위험 압력" },
            { "high pressure", "고압" },
            { "low power", "전력 부족" },
            { "solar panels blocked", "태양광 패널 차단" },
            { "meteor shower", "운석우" },
            { "scanner blocked", "스캐너 차단" },
            { "no meteor shielding", "운석 방어 없음" },
            { "unwired buildings", "미배선 건물" },
            { "wire overload", "전선 과부하" },
            { "no transformer", "변압기 없음" },
            { "broken equipment", "고장 장비" },
            { "damaged equipment", "손상 장비" },
            { "no smart battery", "스마트 배터리 없음" },
            { "coal generator out of coal", "석탄 발전기 연료 없음" },
            { "rock crusher needs metal ore", "암석 분쇄기에 금속 원석 필요" },
            { "suit dock oxygen empty", "대기복 도크 산소 없음" },
            { "suit checkpoint blocking unsafe entry", "대기복 체크포인트가 위험 구역 진입 차단" },
            { "no suit checkpoint", "대기복 체크포인트 없음" },
            { "untapped natural vent", "미활용 자연 분출구" },
            { "hot vent exposed", "뜨거운 분출구 노출" },
            { "wild hatches", "야생 해치" },
            { "hatches need grooming", "해치 돌봄 필요" },
            { "hatches need debris", "해치 먹이 잔해 필요" },
            { "untended crops", "돌보지 않은 작물" },
            { "farm needs fertilizer", "농장에 비료 필요" },
            { "crop wilting", "작물 시듦" },
            { "crop stifled", "작물 성장 저해" },
            { "no insulated tiles", "단열 타일 없음" },
            { "no barracks room", "막사 방 없음" },
            { "no mess hall room", "식당 방 없음" },
            { "printing pod blocked", "프린팅 포드 막힘" },
            { "low algae", "조류 부족" },
            { "loose debris", "흩어진 잔해" },
            { "no auto-sweeper", "자동 청소기 없음" },
            { "no shipping rail", "운송 레일 없음" },
            { "no conveyor chute", "컨베이어 배출구 없음" },
            { "unwired signal switch", "신호 스위치 미배선" },
            { "dry storage full", "건조 저장소 가득 참" },
            { "no storage bin", "저장고 없음" },
            { "low water", "물 부족" },
            { "liquid spill", "액체 유출" },
            { "polluted water stored", "오염된 물 저장됨" },
            { "polluted water offgassing", "오염된 물 가스 방출" },
            { "no bottle emptier", "병 비우개 없음" },
            { "no water sieve", "정수기 없음" },
            { "polluted dirt offgassing", "오염된 흙 가스 방출" },
            { "no compost", "퇴비장 없음" },
            { "pipe phase risk", "배관 상변화 위험" },
            { "pipe burst", "배관 파열" },
            { "reservoir phase risk", "저장소 상변화 위험" },
            { "reservoir burst", "저장소 파열" },
            { "pipe water backed up", "배관 물 역류" },
            { "no liquid reservoir", "액체 저장소 없음" },
            { "unconnected liquid vent", "액체 배출구 미연결" },
            { "gas pipe backed up", "가스 배관 역류" },
            { "no gas reservoir", "가스 저장소 없음" },
            { "unconnected gas pump", "가스 펌프 미연결" },
            { "unconnected gas vent", "가스 배출구 미연결" },
            { "low food", "식량 부족" },
            { "not enough mess tables", "식탁 부족" },
            { "no refrigerator", "냉장고 없음" },
            { "food spoiling", "음식 부패 중" },
            { "food poison", "식중독" },
            { "stale meals", "상한 식사" },
            { "research pending", "연구 대기" },
            { "not enough beds", "침대 부족" },
            { "no outhouse", "화장실 없음" },
            { "no medical cot", "의료 침대 없음" },
            { "no stress relief", "스트레스 해소 시설 없음" },
            { "low decor", "장식 부족" },

            { "Blocked ", "막힘 " },
            { "Assigned to ", "배정됨: " },
            { "Job invalid: target changed or resources missing.", "작업 무효: 대상이 바뀌었거나 자원이 부족합니다." },
            { "Job blocked: no standable work cell. Build floor/ladder access.", "작업 막힘: 설 수 있는 작업 칸이 없습니다. 바닥이나 사다리 접근로를 지으세요." },
            { "Job blocked: no active duplicants.", "작업 막힘: 활동 가능한 복제체가 없습니다." },
            { "Job reachable: ", "작업 도달 가능: " },
            { " steps.", "칸." },
            { "Job unreachable: build ladder/floor/door access to a work cell.", "작업 도달 불가: 작업 칸까지 사다리, 바닥, 문 접근로를 만드세요." },
            { "Job blocked: assigned duplicant is unavailable.", "작업 막힘: 지정된 복제체가 사용할 수 없습니다." }
        };

        private static readonly string[] KoreanKeys = Korean.Keys
            .OrderByDescending(key => key.Length)
            .ToArray();

        public static string LocalizeBlock(string text, ProjectONLanguage language)
        {
            if (language == ProjectONLanguage.English || string.IsNullOrEmpty(text))
            {
                return text;
            }

            string localized = text;
            foreach (string key in KoreanKeys)
            {
                localized = localized.Replace(key, Korean[key]);
            }

            return localized;
        }
    }
}
